#!tsa-virtualenv/bin/python
import sys
from time_series_analysis import AnalyzeSeriesCommand


if __name__ == '__main__':
    analyze_series_command = AnalyzeSeriesCommand()

    (status, message) = analyze_series_command.execute()
    if status > 0 and message:
        sys.stderr.write("stderr: {}\n".format(message))
    sys.exit(status)